### ISSUE TITLE
Vyjimka po prepnuti modu

### ISSUE THREAD

**Issue by kojotak** [kojotak/ARX#50]
Hry -> Dvojhry -> Hry a vylitne vyjimka

09:49:22 [AWT-EventQueue-0] EventService: Exception thrown by;EventService subscriber:BaseProxySubscriber{subscription=class cz.kojotak.arx.domain.mode.Modeveto=falserealSubscriber=cz.kojotak.arx.ui.RecordTable[,0,0,355x672,invalid,alignmentX=0.0,alignmentY=0.0,border=javax.swing.plaf.synth.SynthBorder@5f0bfc54,flags=251658568,maximumSize=,minimumSize=,preferredSize=,autoCreateColumnsFromModel=false,autoResizeMode=AUTO_RESIZE_OFF,cellSelectionEnabled=false,editingColumn=-1,editingRow=-1,gridColor=javax.swing.plaf.ColorUIResource[r=35,g=35,b=36],preferredViewportSize=,rowHeight=18,rowMargin=0,rowSelectionAllowed=true,selectionBackground=DerivedColor(color=57,105,138 parent=nimbusSelectionBackground offsets=0.0,0.0,0.0,0 pColor=57,105,138,selectionForeground=DerivedColor(color=255,255,255 parent=nimbusLightBackground offsets=0.0,0.0,0.0,0 pColor=255,255,255,showHorizontalLines=false,showVerticalLines=false], subscriptionMethod=public void cz.kojotak.arx.ui.RecordTable.onModeChange(cz.kojotak.arx.domain.mode.Mode), referenceStrength=WEAK, eventService=org.bushe.swing.event.SwingEventService@183b24c4}.  Subscriber class:class org.bushe.swing.event.annotation.BaseProxySubscriberorg.bushe.swing.exception.SwingException: Exception handling event topic event class=cz.kojotak.arx.domain.mode.SinglePlayerMode, event=SinglePlayerMode, topic=null, eventObj=null
org.bushe.swing.exception.SwingException: Exception handling event topic event class=cz.kojotak.arx.domain.mode.SinglePlayerMode, event=SinglePlayerMode, topic=null, eventObj=null
	at org.bushe.swing.event.ThreadSafeEventService.handleException(ThreadSafeEventService.java:2021)
	at org.bushe.swing.event.ThreadSafeEventService.handleException(ThreadSafeEventService.java:2009)
	at org.bushe.swing.event.ThreadSafeEventService.publish(ThreadSafeEventService.java:975)
	at org.bushe.swing.event.SwingEventService.publish(SwingEventService.java:78)
	at org.bushe.swing.event.ThreadSafeEventService.publish(ThreadSafeEventService.java:904)
	at org.bushe.swing.event.EventBus.publish(EventBus.java:57)
	at cz.kojotak.arx.ui.listener.ModeChangeListener.actionPerformed(ModeChangeListener.java:47)
...
Caused by: java.lang.RuntimeException: InvocationTargetException when invoking annotated method from EventService publication.  Event class:class cz.kojotak.arx.domain.mode.SinglePlayerMode, Event:SinglePlayerMode, subscriber:cz.kojotak.arx.ui.RecordTable[,0,0,355x672,invalid,alignmentX=0.0,alignmentY=0.0,border=javax.swing.plaf.synth.SynthBorder@5f0bfc54,flags=251658568,maximumSize=,minimumSize=,preferredSize=,autoCreateColumnsFromModel=false,autoResizeMode=AUTO_RESIZE_OFF,cellSelectionEnabled=false,editingColumn=-1,editingRow=-1,gridColor=javax.swing.plaf.ColorUIResource[r=35,g=35,b=36],preferredViewportSize=,rowHeight=18,rowMargin=0,rowSelectionAllowed=true,selectionBackground=DerivedColor(color=57,105,138 parent=nimbusSelectionBackground offsets=0.0,0.0,0.0,0 pColor=57,105,138,selectionForeground=DerivedColor(color=255,255,255 parent=nimbusLightBackground offsets=0.0,0.0,0.0,0 pColor=255,255,255,showHorizontalLines=false,showVerticalLines=false], subscription Method=public void cz.kojotak.arx.ui.RecordTable.onModeChange(cz.kojotak.arx.domain.mode.Mode)
	... 
Caused by: java.lang.reflect.InvocationTargetException
	... 
Caused by: java.lang.IndexOutOfBoundsException: column beyond range of TableModel
	at java.desktop/javax.swing.DefaultRowSorter.checkColumn(DefaultRowSorter.java:1234)
	at java.desktop/javax.swing.DefaultRowSorter.setSortable(DefaultRowSorter.java:257)
	at org.jdesktop.swingx.sort.DefaultSortController.setSortable(DefaultSortController.java:90)
	at org.jdesktop.swingx.JXTable.configureSorterProperties(JXTable.java:1629)
	at org.jdesktop.swingx.JXTable.setRowSorter(JXTable.java:1608)
	at org.jdesktop.swingx.JXTable.setModel(JXTable.java:1551)
	at cz.kojotak.arx.ui.RecordTable.onModeChange(RecordTable.java:88)
	... 46 more

**Comment by kojotak** [comment]
duplikuje #59
